/** Operator schema lookup over the lazily loaded metadata.json (generated by scripts/gen_onnx_metadata.py). */
import type { OpSchema } from "./types";

type FormalRec = [string, string, string, number];
type AttrRec = [string, string, string, number, (string | number | (string | number)[])?];
interface VersionRec {
  v: number;
  d?: string;
  i?: FormalRec[];
  o?: FormalRec[];
  a?: AttrRec[];
  t?: [string, string, number][];
  x?: number;
}
export interface Metadata {
  v: string;
  types: string[][];
  ops: Record<string, Record<string, VersionRec[]>>;
}

let loading: Promise<Metadata> | null = null;
let loaded: Metadata | null = null;

export function loadMetadata(): Promise<Metadata> {
  return (loading ??= import("./metadata.json").then((m) => (loaded = m.default as unknown as Metadata)));
}

export const normDomain = (d: string): string => (d === "" ? "ai.onnx" : d);

const OPTION = ["single", "optional", "variadic"] as const;

/** synchronous lookup; metadata must have been loaded (see loadMetadata) */
export function lookupSchemaSync(meta: Metadata, domain: string, op: string, opset: number | null): OpSchema | null {
  const recs = meta.ops[normDomain(domain)]?.[op];
  if (!recs?.length) return null;
  let idx = -1;
  for (let i = 0; i < recs.length; i++) if (opset == null || recs[i]!.v <= opset) idx = i;
  if (idx < 0) idx = 0; // opset older than any definition: show the oldest
  const pick = <K extends "d" | "i" | "o" | "a" | "t">(k: K): NonNullable<VersionRec[K]> | undefined => {
    for (let j = idx; j >= 0; j--) if (recs[j]![k] !== undefined) return recs[j]![k] as NonNullable<VersionRec[K]>;
    return undefined;
  };
  const rec = recs[idx]!;
  const constraints = (pick("t") ?? []).map(([name, description, ti]) => ({ name, description, types: meta.types[ti] ?? [] }));
  const byName = new Map(constraints.map((c) => [c.name, c.types]));
  const formal = (f: FormalRec) => ({
    name: f[0], description: f[1], typeStr: f[2], types: byName.get(f[2]) ?? [f[2]], option: OPTION[f[3]] ?? "single",
  });
  return {
    domain: normDomain(domain),
    name: op,
    sinceVersion: rec.v,
    doc: pick("d") ?? "",
    inputs: (pick("i") ?? []).map(formal),
    outputs: (pick("o") ?? []).map(formal),
    attributes: (pick("a") ?? []).map((a) => ({
      name: a[0], description: a[1], type: a[2], required: !!a[3], ...(a[4] !== undefined ? { default: a[4] } : {}),
    })),
    typeConstraints: constraints,
    versions: recs.map((r) => r.v),
  };
}

export async function lookupSchema(domain: string, op: string, opset: number | null): Promise<OpSchema | null> {
  const meta = loaded ?? (await loadMetadata());
  return lookupSchemaSync(meta, domain, op, opset);
}

/** names of formal inputs/outputs, used to label node inputs when the static role table has no entry */
export function formalNames(meta: Metadata, domain: string, op: string, opset: number | null) {
  const s = lookupSchemaSync(meta, domain, op, opset);
  return s ? { inputs: s.inputs.map((p) => [p.name, p.option] as const), outputs: s.outputs.map((p) => [p.name, p.option] as const) } : null;
}
